import React, { useRef, useState, useEffect } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import pageStyles from '@styles/Page.module.css';
import styles from './Map.module.css';
import Header from '@components/organisms/Header';
import MapController from '@components/organisms/MapController';
import 'mapbox-gl/dist/mapbox-gl.css';
import mapboxgl, { Map as MapBoxMap, LngLat } from 'mapbox-gl';

mapboxgl.accessToken = process.env.MAPBOX_ACCESS_TOKEN || '';

const Map: NextPage = () => {
    const mapContainer = useRef<HTMLDivElement>(null);
    const map = useRef<MapBoxMap>(null);

    const [coords, setCoords] = useState<LngLat>(new LngLat(73.371454, 54.985974));
    const [zoom, setZoom] = useState(11);

    useEffect(() => {
        if (!mapContainer.current) return;
        if (map.current) return;

        const mapboxMap = new MapBoxMap({
            container: mapContainer.current,
            style: 'mapbox://styles/mapbox/streets-v11',
            center: coords,
            zoom: zoom,
        });
        mapboxMap.on('move', () => {
            setCoords(mapboxMap.getCenter());
            setZoom(mapboxMap.getZoom());
        });

        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        map.current = mapboxMap;
    }, [mapContainer.current]);

    return (
        <div className={pageStyles.container}>
            <Head>
                <title>Карта</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Header />

            <main className={styles.container__main}>
                <div ref={mapContainer} className={styles.main__map}>
                    <MapController
                        className={styles.map__controller}
                        onZoomIn={() => map.current?.flyTo({ zoom: zoom + 1 })}
                        onZoomOut={() => map.current?.flyTo({ zoom: zoom - 1 })}
                    />
                </div>
            </main>
        </div>
    );
};

export default Map;
