import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import pageStyles from '@styles/Page.module.css';
import styles from './Map.module.css';
import Header from '@components/organisms/Header';
import MapController from '@components/organisms/MapController';

const Map: NextPage = () => {
    return (
        <div className={pageStyles.container}>
            <Head>
                <title>Карта</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Header />

            <main className={styles.container__main}>
                <MapController className={styles.main__controller} />
            </main>
        </div>
    );
};

export default Map;
