import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '@styles/Home.module.css';
import Header from '@components/organisms/Header';

const Subscriptions: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Избранные датчики</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Header />
        </div>
    );
};

export default Subscriptions;
