import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '@components/organisms/Header';
import pageStyles from '@styles/Page.module.css';

const Saved: NextPage = () => {
    return (
        <div className={pageStyles.container}>
            <Head>
                <title>Подписки</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Header />
        </div>
    );
};

export default Saved;
