import React, { useEffect, useMemo, useRef, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import pageStyles from '@styles/Page.module.css';
import styles from './Map.module.css';
import Header from '@components/organisms/Header';
import MapController from '@components/organisms/MapController';
import 'mapbox-gl/dist/mapbox-gl.css';
import mapboxgl, { LngLat, Map as MapBoxMap, Marker } from 'mapbox-gl';
import { useSensors } from '@hooks/Map.hooks';
import { Spinner } from '@chakra-ui/react';
import theme from '@styles/theme';
import { ISensorValue, ValueType } from '@api/models/SensorValue';

mapboxgl.accessToken = process.env.MAPBOX_ACCESS_TOKEN || '';

const Map: NextPage = () => {
    const mapContainer = useRef<HTMLDivElement>(null);
    const map = useRef<MapBoxMap>(null);

    const [coords, setCoords] = useState<LngLat>(new LngLat(73.371454, 54.985974));
    const [zoom, setZoom] = useState(11);

    useEffect(() => {
        if (!mapContainer.current) return;
        if (map.current) return;

        const mapboxMap = new MapBoxMap({
            container: mapContainer.current,
            style: 'mapbox://styles/mapbox/streets-v11',
            center: coords,
            zoom: zoom,
        });
        mapboxMap.on('move', () => {
            setCoords(mapboxMap.getCenter());
            setZoom(mapboxMap.getZoom());
        });

        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        map.current = mapboxMap;
        getSensors();
    }, [mapContainer.current]);

    const { isLoading, sensors, error, getSensors } = useSensors();

    const [renderedMarkers, setRenderedMarkers] = useState<Array<Marker>>([]);

    const getColor = (sensorValue: ISensorValue | undefined) => {
        if (!sensorValue) return theme.colors.lightgrey;

        // eslint-disable-next-line default-case
        switch (sensorValue.type) {
            case ValueType.PM25: {
                if (sensorValue.value <= 15.4) return theme.colors.green;
                if (sensorValue.value > 15.4 && sensorValue.value <= 40.4) return theme.colors.yellow;
                return theme.colors.red;
            }
            case ValueType.PM10: {
                if (sensorValue.value <= 54) return theme.colors.green;
                if (sensorValue.value > 54 && sensorValue.value <= 154) return theme.colors.yellow;
                return theme.colors.red;
            }
        }
    };

    const currentMarkers = useMemo(
        () =>
            sensors?.map(
                sensor =>
                    sensor.location &&
                    new mapboxgl.Marker({ color: getColor(sensor.lastValue) })
                        .setLngLat([sensor.location.coordinates[0], sensor.location.coordinates[1]])
                        .setPopup(
                            new mapboxgl.Popup({ offset: 25 }).setHTML(
                                `<h3>Модель: ${sensor.model}</h3>` +
                                    `<h3>Версия: ${sensor.version}</h3>` +
                                    `<h3>Автор: ${sensor.name}</h3>` +
                                    `${
                                        sensor.lastValue
                                            ? `<h3>
                                                ${sensor.lastValue.type}: ${sensor.lastValue.value}
                                            </h3>`
                                            : 'Измерения отсутсвуют'
                                    }`,
                            ),
                        ),
            ),
        [sensors],
    );

    useEffect(() => {
        renderedMarkers.forEach(marker => marker.remove());

        const currentMap = map.current;
        if (currentMap) {
            currentMarkers?.forEach(marker => {
                if (!marker) return;

                marker.addTo(currentMap);
                setRenderedMarkers(prevRenderedMarkers => [...prevRenderedMarkers, marker]);
            });
        }
    }, [currentMarkers, map.current]);

    return (
        <div className={pageStyles.container}>
            <Head>
                <title>Карта</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Header />

            <main className={styles.container__main}>
                <div ref={mapContainer} className={styles.main__map}>
                    {isLoading && (
                        <div className={styles.map__overlay}>
                            <Spinner color={'green'} size={'xl'} />
                        </div>
                    )}
                    <MapController
                        className={styles.map__controller}
                        onZoomIn={() => map.current?.flyTo({ zoom: zoom + 1 })}
                        onZoomOut={() => map.current?.flyTo({ zoom: zoom - 1 })}
                    />
                </div>
            </main>
        </div>
    );
};

export default Map;
