import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import pageStyles from '@styles/Page.module.css';
import styles from './Map.module.css';
import Header from '@components/organisms/Header';
import MapController from '@components/organisms/MapController';
import 'mapbox-gl/dist/mapbox-gl.css';
import { useSensors } from '@pages/map/Map.hooks';
import { Spinner } from '@chakra-ui/react';
import MapComponent from '@components/organisms/Map';
import { MapProvider, useMapContext } from '@context/MapContext';

const Map: NextPage = () => {
    const { map, zoom } = useMapContext();
    const { isLoading, sensors, error, getSensors } = useSensors();

    /*useEffect(() => {
        getSensors();
    }, []);

    const [renderedMarkers, setRenderedMarkers] = useState<Array<Marker>>([]);

    const currentMarkers = useMemo(
        () =>
            sensors?.map(
                sensor =>
                    sensor.location &&
                    new Marker({ color: theme.colors.green }).setLngLat([
                        sensor.location.coordinates[0],
                        sensor.location.coordinates[1],
                    ]),
            ),
        [sensors],
    );

    useEffect(() => {
        renderedMarkers.forEach(marker => marker.remove());

        if (map) {
            currentMarkers?.forEach(marker => {
                if (!marker) return;

                marker.addTo(map);
                setRenderedMarkers(prevRenderedMarkers => [...prevRenderedMarkers, marker]);
            });
        }
    }, [currentMarkers, map]);*/

    return (
        <div className={pageStyles.container}>
            <Head>
                <title>Карта</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Header />

            <main className={styles.container__main}>
                <MapComponent className={styles.main__map}>
                    {isLoading && (
                        <div className={styles.map__overlay}>
                            <Spinner color={'green'} size={'xl'} />
                        </div>
                    )}
                    <MapController
                        className={styles.map__controller}
                        onZoomIn={() => map?.flyTo({ zoom: zoom + 1 })}
                        onZoomOut={() => map?.flyTo({ zoom: zoom - 1 })}
                    />
                </MapComponent>
            </main>
        </div>
    );
};

export default () => (
    <MapProvider>
        <Map />
    </MapProvider>
);
