import React, { useEffect } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
    useEffect(() => {
        window.location.href += '/map';
    }, []);

    return (
        <Head>
            <title>Bip-Bap</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
        </Head>
    );
};

export default Home;
